# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/devise-encryptable/all/devise-encryptable.rbi
#
# devise-encryptable-0.2.0

module Devise
  def encryptor; end
  def encryptor=(obj); end
  def self.encryptor; end
  def self.encryptor=(obj); end
end
module Devise::Encryptable
end
module Devise::Encryptable::Encryptors
end
class Devise::Mapping
  def encryptable?; end
end
