# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rubocop-git/all/rubocop-git.rbi
#
# rubocop-git-0.1.3

module RuboCop
end
module RuboCop::Git
end
