---
linters:
  ErbSafety:
    enabled: true
  FinalNewline:
    enabled: true
  SelfClosingTag:
    enabled: true
  SpaceAroundErbTag:
    enabled: true
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Style/FrozenStringLiteralComment:
        Enabled: false
      Layout/LineLength:
        Enabled: false
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Layout/TrailingWhitespace:
        Enabled: false
      Naming/FileName:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
