name: Pronto

on:
  - pull_request

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: Gemfile.tools
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.6'
          bundler-cache: true
      - name: Run Pronto
        run: |
          PRONTO_PULL_REQUEST_ID="$(jq --raw-output .number "$GITHUB_EVENT_PATH")" PRONTO_GITHUB_ACCESS_TOKEN=${{ secrets.PRONTO_GITHUB_ACCESS_TOKEN }} bundle exec pronto run -f github_status github_pr -c origin/${{ github.base_ref }}
