name: Pronto

on:
  - pull_request

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: Gemfile.tools
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.6'
      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.tools.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --gemfile=Gemfile.tools --jobs 4 --retry 3
      - name: Run Pronto
        run: |
          bundle exec pronto run -c origin/main -f github_status -f github_pr_review --exit-code

