name: Ruby

on:
  - pull_request

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby 2.6.6 && Run/cache bundle install
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.6'
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec spec
