name: Ruby

on:
  - pull_request

env:
  CC_TEST_REPORTER_URL: https://codeclimate.com/downloads/test-reporter/test-reporter-0.7.0-linux-amd64

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby 2.6.6 
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.6'
      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Set ENV for Code Climate
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/$GITHUB_HEAD_REF:refs/remotes/origin/$GITHUB_HEAD_REF
          export GIT_BRANCH="$GITHUB_HEAD_REF"
          export GIT_COMMIT_SHA="$(git rev-parse origin/$GITHUB_HEAD_REF)"
      - name: Install Code Climate reporter
        run: |
          curl -L $CC_TEST_REPORTER_URL > cc-test-reporter
          chmod +x cc-test-reporter
      - name: Run tests
        run: |
          ./cc-test-reporter before-build
          bundle exec rspec
          ./cc-test-reporter after-build --coverage-input-type simplecov --exit-code $?
